package com.zjt.common.inter;

import com.zjt.common.entity.SysRolePermission2;
import com.zjt.common.entity.SysRolePermission2Example;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SysRolePermission2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    long countByExample(SysRolePermission2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int deleteByExample(SysRolePermission2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int insert(SysRolePermission2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int insertSelective(SysRolePermission2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    List<SysRolePermission2> selectByExample(SysRolePermission2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    SysRolePermission2 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysRolePermission2 record, @Param("example") SysRolePermission2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int updateByExample(@Param("record") SysRolePermission2 record, @Param("example") SysRolePermission2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int updateByPrimaryKeySelective(SysRolePermission2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_role_permission2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int updateByPrimaryKey(SysRolePermission2 record);



}