package com.zjt.common.inter;

import com.zjt.common.entity.SysUser2;
import com.zjt.common.entity.SysUser2Example;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SysUser2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    long countByExample(SysUser2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int deleteByExample(SysUser2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int insert(SysUser2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int insertSelective(SysUser2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    List<SysUser2> selectByExample(SysUser2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    SysUser2 selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysUser2 record, @Param("example") SysUser2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int updateByExample(@Param("record") SysUser2 record, @Param("example") SysUser2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int updateByPrimaryKeySelective(SysUser2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int updateByPrimaryKey(SysUser2 record);

    void selectByExample();
}