package com.zjt.common.inter;

import com.zjt.common.entity.SysUserRole2;
import com.zjt.common.entity.SysUserRole2Example;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface SysUserRole2Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    long countByExample(SysUserRole2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int deleteByExample(SysUserRole2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int insert(SysUserRole2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int insertSelective(SysUserRole2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    List<SysUserRole2> selectByExample(SysUserRole2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    SysUserRole2 selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysUserRole2 record, @Param("example") SysUserRole2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int updateByExample(@Param("record") SysUserRole2 record, @Param("example") SysUserRole2Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int updateByPrimaryKeySelective(SysUserRole2 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_role2
     *
     * @mbg.generated Sun Apr 19 09:54:50 CST 2020
     */
    int updateByPrimaryKey(SysUserRole2 record);
}